package key;

import com.wx.crypto.Crypter;
import com.wx.crypto.CryptoException;

/**
 * Interface of a key buffer. A key buffer can initialize a {@code Crypter} key based on the content of its buffer.
 * <p>
 * The content of the buffer is created using {@link #feed(String)}.
 *
 * @author canale
 */
public interface KeyBuffer {

    /**
     * Feed this buffer's content. Every time the buffer is fed with new content, the key generated by {@link
     * #loadKeyIn(Crypter)} will differ.
     *
     * @param value Content to feed to this buffer
     *
     * @throws CryptoException
     */
    void feed(String value) throws CryptoException;

    /**
     * Generate a key for the given {@code Crypter} based on this buffer's content.
     *
     * @param crypter {@code Crypter} to initialize
     *
     * @throws CryptoException
     */
    void loadKeyIn(Crypter crypter) throws CryptoException;

}
